// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewrEfKdLmd4vfo-lNwDlSjizenUulyVw',
    appId: '1:473680783521:web:7dc8266022621a8805a8e0',
    messagingSenderId: '473680783521',
    projectId: 'myquickbytes-9e237',
    authDomain: 'myquickbytes-9e237.firebaseapp.com',
    storageBucket: 'myquickbytes-9e237.appspot.com',
    measurementId: 'G-498TKKBXVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPd6vO87aYlGxQboBMdhNpdn7JQVKY4G8',
    appId: '1:473680783521:android:065266792024734c05a8e0',
    messagingSenderId: '473680783521',
    projectId: 'myquickbytes-9e237',
    storageBucket: 'myquickbytes-9e237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5wzXxPmkyw_N-EO8K3sgG9s-OdkCOOE',
    appId: '1:473680783521:ios:601e3c395b6f7b1b05a8e0',
    messagingSenderId: '473680783521',
    projectId: 'myquickbytes-9e237',
    storageBucket: 'myquickbytes-9e237.appspot.com',
    iosBundleId: 'com.example.madFastfoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCewrEfKdLmd4vfo-lNwDlSjizenUulyVw',
    appId: '1:473680783521:web:507482b6228a66a605a8e0',
    messagingSenderId: '473680783521',
    projectId: 'myquickbytes-9e237',
    authDomain: 'myquickbytes-9e237.firebaseapp.com',
    storageBucket: 'myquickbytes-9e237.appspot.com',
    measurementId: 'G-VLQ3QZV1K6',
  );
}
